apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- nginx-application.yaml
images:
  - name: nginx
    newName: nginx
    newTag: 1.22.1
replicas:
  - name: nginx-deployment
    count: 1

commonAnnotations:
  kubernetes.io/change-cause: "Initial deployment with 1.18.0"
